// ---------------------------------------------------------------------------
// ControlUIClaw SDK — Public API
// ---------------------------------------------------------------------------

export { ControlUIClaw, GatewayRequestError, SDK_VERSION } from "./client.js";

// Crypto utilities (for advanced / custom auth flows)
export {
  getOrCreateDeviceIdentity,
  clearCachedIdentity,
  buildDeviceAuthPayload,
  signPayload,
  base64UrlEncode,
  base64UrlDecode,
} from "./crypto.js";

// Enums
export { Channel } from "./types.js";

// Types
export type {
  InitOptions,
  ConnectResult,
  ConnectErrorDetails,
  HealthEvent,
  ChatEvent,
  AskQuestion,
  AskOption,
  AskAnswer,
  ChatErrorKind,
  Unsubscribe,
  ConnectionState,
  Session,
  ChatMessage,
  ContentBlock,
  ChatChoice,
  ChatHistoryResult,
  ClientInfo,
  DeviceIdentity,
  HelloPayload,
  SendPromptOptions,
  SendImagePromptOptions,
  ImageAttachment,
  TokenUsage,
  ThinkingLevel,
  FastMode,
  ThinkingLevelOption,
  SessionPatchParams,
  ChannelsStatusResult,
  ChannelsChannelData,
  ChannelAccountSnapshot,
  ChannelUiMeta,
  WhatsAppChannelStatus,
  TelegramChannelStatus,
  DiscordChannelStatus,
  SlackChannelStatus,
  SignalChannelStatus,
  IMessageChannelStatus,
  BlueBubblesChannelStatus,
  GoogleChatChannelStatus,
  NostrChannelStatus,
  ChannelLogoutResult,
  ChannelLogoutOptions,
  WhatsAppLoginOptions,
  WhatsAppLoginStatusEvent,
  WhatsAppLoginStep,
  ChannelStatusEvent,
  SkillStatusEntry,
  SkillStatusReport,
  SkillUpdateResult,
  CronJob,
  CronJobCreate,
  CronJobPatch,
  CronJobState,
  CronJobsListResult,
  CronRemoveResult,
  CronSchedule,
  CronScheduleKind,
  CronScheduleCron,
  CronScheduleEvery,
  CronScheduleAt,
  CronPayload,
  CronPayloadAgentTurn,
  CronPayloadSystemEvent,
  CronPayloadKind,
  CronDelivery,
  CronDeliveryMode,
  CronSessionTarget,
  CronWakeMode,
  CronThinkingLevel,
  CronEveryUnit,
  CronRunMode,
  CronRunResult,
  CronRunsOptions,
  CronRunsResult,
  CronRunLogEntry,
  CronStatusResult,
} from "./types.js";
